version: "3.3" # optional since v1.27.0
services:
  pwnybot:
    restart: always
    build: .
    environment:
      - DISCORD_TOKEN
      - GUILD_IDS
      - CTF_CATEGORY_CHANNELS
      - CTF_ROLES
      - UIUC_ROLES
      - MODERATOR_ROLES
    volumes:
      - ./.env:/bot/.env
      - ./config.yml:/bot/config.yml
  db:
    image: postgres
    environment:
      POSTGRES_USER: sigpwny
      POSTGRES_PASSWORD: sigpwny
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
