import os

AUTOGENERATED_CHANNELS = {'general': 'general',
                          'logs': 'logs-📝', 'access': 'access-requests-✔️'}
ARCHIVE_CATEGORY = 'ctf-archive'
CTF_PREFIX = 'ctf '
INTERNAL_CTFD_URL = 'http://localhost:8000'
GUILD_IDS = list(map(int, os.getenv('GUILD_IDS').split(',')))
DISCORD_TOKEN = os.getenv('DISCORD_TOKEN')
CTFD_TOKEN = os.getenv('CTFD_TOKEN')
DEFAULT_ARCHIVE_ID = int(os.getenv('DEFAULT_ARCHIVE_ID'))

EMOTE_FROM = "<:pwnyPortalFrom:846826010561478657> "
EMOTE_TO = "<:pwnyPortalTo:846826010241794102> "
CTF_ROLE_ID = 839240304247046165  # uiuctf-2021
UIUC_ROLE_ID = 613249703085342723
